use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_OLTP_STATUS_FREQUENCIA @DATA_CARGA DATE
AS
BEGIN
	DELETE TB_AUX_STATUS_FREQUENCIA
	WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_STATUS_FREQUENCIA(COD_FREQUENCIA,DATA_CARGA,FREQUENCIA)
	SELECT ID_ALUNO,@DATA_CARGA,FREQUENCIA FROM TB_FREQUENCIA
END

DECLARE @DATE DATE 
SET @DATE = GETDATE()

EXEC SP_OLTP_STATUS_FREQUENCIA @DATE

SELECT