use bd_frequencia_escola;
DROP TABLE TB_ESCOLA


CREATE TABLE TB_ESCOLA (
	ID_ESCOLA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL)

INSERT INTO TB_ESCOLA(ID_ESCOLA,NOME) VALUES(1,'GUILHERME')


drop table TB_AUX_FREQUENCIA

CREATE TABLE TB_TURMA(
	ID_TURMA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ANO_LETIVO INT NOT NULL,
	ID_ESCOLA INT REFERENCES TB_ESCOLA)

INSERT INTO TB_TURMA(ID_TURMA,NOME,ANO_LETIVO,ID_ESCOLA) VALUES (10,'TURMA A1',2022,1)

CREATE TABLE TB_ALUNO(
	ID_ALUNO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ID_TURMA INT REFERENCES TB_TURMA(ID_TURMA))

INSERT INTO TB_ALUNO(ID_ALUNO,NOME,ID_TURMA) VALUES(100,'MATHEUS',10)

SELECT * FROM TB_ALUNO


CREATE TABLE TB_DISCIPLINA(
	ID_DISCIPLINA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL)

INSERT INTO TB_DISCIPLINA(ID_DISCIPLINA,NOME)VALUES(1,'PORTUGUES')

CREATE TABLE TB_TURMA_DISCIPLINA(
	ID_TURMA INT NOT NULL,
	ID_DISCIPLINA INT NOT NULL,
	CONSTRAINT FK_TURMA FOREIGN KEY (ID_TURMA) REFERENCES TB_TURMA (ID_TURMA),
	CONSTRAINT FK_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID_DISCIPLINA)
				)

	INSERT INTO TB_TURMA_DISCIPLINA(ID_DISCIPLINA,ID_TURMA) VALUES(1,10)

	SELECT * FROM TB_TURMA_DISCIPLINA
	
	DROP TABLE FREQUENCIA_STATUS

CREATE TABLE FREQUENCIA_STATUS(
	ID_FREQUENCIA_STATUS INT NOT NULL PRIMARY KEY,
	FREQUENCIA CHAR(5) CHECK ( FREQUENCIA IN('P','F')),
	)

INSERT INTO FREQUENCIA_STATUS(ID_FREQUENCIA_STATUS,FREQUENCIA) VALUES(1,'P'),(2,'F')

SELECT * FROM FREQUENCIA_STATUS

	DROP TABLE TB_FREQUENCIA


CREATE TABLE TB_FREQUENCIA(
	ID_FREQUENCIA INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	ID_TURMA INT NOT NULL,
	ID_DISCIPLINA INT NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_FREQUENCIA_STATUS INT NOT NULL,
	DATA DATETIME NOT NULL
	CONSTRAINT FK_TURMA1 FOREIGN KEY (ID_TURMA) REFERENCES TB_TURMA (ID_TURMA),
	CONSTRAINT FK_DISCIPLINA2 FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID_DISCIPLINA),
	CONSTRAINT FK_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES TB_ALUNO (ID_ALUNO),
	CONSTRAINT FK_FREQUENCIA_STATUS FOREIGN KEY (ID_FREQUENCIA_STATUS) REFERENCES FREQUENCIA_STATUS(ID_FREQUENCIA_STATUS)
	)


	DELETE TB_FREQUENCIA

	INSERT INTO TB_FREQUENCIA VALUES (10,1,100,1,GETDATE())
	INSERT INTO TB_FREQUENCIA VALUES (10,1,100,2,GETDATE())
	INSERT INTO TB_FREQUENCIA VALUES (10,1,100,1,GETDATE())
	INSERT INTO TB_FREQUENCIA VALUES (10,1,100,2,GETDATE())
	INSERT INTO TB_FREQUENCIA VALUES (10,1,100,1,GETDATE())

	SELECT * FROM TB_FREQUENCIA



SELECT * FROM TB_ALUNO

SELECT * FROM TB_DISCIPLINA

SELECT * FROM TB_ESCOLA

SELECT * FROM TB_TURMA

SELECT * FROM TB_TURMA_DISCIPLINA

SELECT * FROM TB_FREQUENCIA