use bd_frequencia_escola

DROP TABLE IF EXISTS TB_AUX_STATUS_FREQUENCIA
DROP TABLE IF EXISTS TB_AUX_FREQUENCIA
DROP TABLE IF EXISTS TB_AUX_ALUNO
DROP TABLE IF EXISTS TB_AUX_DISCIPLINA
DROP TABLE IF EXISTS TB_AUX_ESCOLA
DROP TABLE IF EXISTS TB_AUX_TURMA
DROP TABLE IF EXISTS TB_VIO_FREQUENCIA


CREATE TABLE TB_AUX_TURMA(
	DATA_CARGA DATETIME NOT NULL,
	COD_TURMA INT NULL,
	NOME_TURMA VARCHAR(45))

CREATE TABLE TB_AUX_ESCOLA(
	DATA_CARGA DATETIME NOT NULL,
	COD_ESCOLA INT NULL,
	NOME_ESCOLA VARCHAR(45))

CREATE TABLE TB_AUX_ALUNO(
	DATA_CARGA DATETIME NOT NULL,
	COD_ALUNO INT NULL,
	NOME_ALUNO VARCHAR(45) NULL)

CREATE TABLE TB_AUX_DISCIPLINA(
	DATA_CARGA DATETIME NOT NULL,
	COD_DISCIPLINA INT NULL,
	NOME_DISCIPLINA VARCHAR(45))

CREATE TABLE TB_AUX_STATUS_FREQUENCIA(
	DATA_CARGA DATETIME NOT NULL,
	FREQUENCIA CHAR(5) CHECK(FREQUENCIA IN('P','F')) NULL,
	COD_FREQUENCIA INT NULL
		)


CREATE TABLE TB_AUX_FREQUENCIA(
	DATA_CARGA DATETIME NOT NULL,
	COD_TURMA INT NULL,
	COD_ALUNO INT NULL,
	COD_DISCIPLINA INT NULL,
	COD_ESCOLA INT NULL,
	COD_STATUS_FREQUENCIA INT NULL,
	DATA_FREQUENCIA DATETIME NULL )


CREATE TABLE TB_VIO_FREQUENCIA(
	ID_VIOLACAO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	COD_TURMA INT NULL,
	COD_ALUNO INT NULL,
	COD_DISCIPLINA INT NULL,
	COD_ESCOLA INT NULL,
	COD_STATUS_FREQUENCIA INT NULL,
	DATA_FREQUENCIA DATETIME NULL,
	DATA_ERRO DATETIME,
	VIOLACAO VARCHAR(150) NULL)