use bd_frequencia_escola

DELETE TB_DISCIPLINA
INSERT INTO TB_DISCIPLINA ( NOME) VALUES ('MATEMATICA')
INSERT INTO TB_DISCIPLINA ( NOME) VALUES ('PORTUGUES')
INSERT INTO TB_DISCIPLINA ( NOME) VALUES ('FILOSOFIA')


SELECT * FROM TB_DISCIPLINA