use bd_frequencia_escola

INSERT INTO TB_DISCIPLINA (ID_DISCIPLINA, NOME) VALUES (1,'MATEMATICA')
INSERT INTO TB_DISCIPLINA (ID_DISCIPLINA, NOME) VALUES (2,'PORTUGUES')
INSERT INTO TB_DISCIPLINA (ID_DISCIPLINA, NOME) VALUES (1,'FILOSOFIA')
