use bd_frequencia_escola


INSERT INTO TB_ALUNO (ID_ALUNO, NOME, ID_TURMA) VALUES (1,'PEDRO ALVES',1)
INSERT INTO TB_ALUNO (ID_ALUNO, NOME, ID_TURMA) VALUES (2,'MARCOS SILVA',1)
INSERT INTO TB_ALUNO (ID_ALUNO, NOME, ID_TURMA) VALUES (3,'PAULA MORAES',1)