use bd_frequencia_escola

INSERT INTO TB_TURMA ( NOME, ANO_LETIVO, ID_ESCOLA) VALUES ('8º ano', 2022, 1)

INSERT INTO TB_TURMA ( NOME, ANO_LETIVO, ID_ESCOLA) VALUES ('9º ano', 2022, 1)


INSERT INTO TB_TURMA ( NOME, ANO_LETIVO, ID_ESCOLA) VALUES ('5º ano', 2022, 2)

INSERT INTO TB_TURMA ( NOME, ANO_LETIVO, ID_ESCOLA) VALUES ('7º ano', 2022, 2)


SELECT * FROM TB_TURMA