use bd_frequencia_escola



DELETE TB_FREQUENCIA

select * from TB_ALUNO

INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,5,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,2,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,10,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,3,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,8,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,2,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,9,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,4,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,3,3,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (1,1,1,1,GETDATE())


INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,5,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,2,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,10,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,3,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,8,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,2,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,9,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,4,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,3,3,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (2,1,1,1,GETDATE())


INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,30,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,20,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,6,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,20,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,15,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,7,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,11,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,10,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,3,27,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,30,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,20,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,9,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,40,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,20,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,9,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,7,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,2,5,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,7,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,3,8,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (3,1,20,1,GETDATE())

INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,30,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,20,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,6,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,2,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,20,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,9,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,1,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,8,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,3,3,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,6,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,7,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,5,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,40,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,20,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,11,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,30,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,2,4,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,10,1,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,3,5,2,GETDATE())
INSERT INTO TB_FREQUENCIA(ID_TURMA,ID_DISCIPLINA,ID_ALUNO,ID_FREQUENCIA_STATUS,DATA) VALUES (4,1,2,1,GETDATE())





SELECT * FROM TB_FREQUENCIA

