use bd_frequencia_escola


INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PEDRO ALVES',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS SILVA',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PAULA MORAES',1)