use bd_frequencia_escola

INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (2, 1)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (2, 2)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (2, 3)

INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (3, 1)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (3, 2)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (3, 3)

INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (4, 1)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (4, 2)
INSERT INTO TB_TURMA_DISCIPLINA (ID_TURMA,ID_DISCIPLINA) VALUES (4, 3)


select * from TB_TURMA_DISCIPLINA