use bd_frequencia_escola

INSERT INTO TB_FREQUENCIA (ID_FREQUENCIA, FREQUENCIA, ID_TURMA, ID_DISCIPLINA, ID_ALUNO, DATA) VALUES (1, 'P', 1, 1, 1, '20/05/22')
INSERT INTO TB_FREQUENCIA (ID_FREQUENCIA, FREQUENCIA, ID_TURMA, ID_DISCIPLINA, ID_ALUNO, DATA) VALUES (2, 'F', 1, 1, 2, '20/05/22')
INSERT INTO TB_FREQUENCIA (ID_FREQUENCIA, FREQUENCIA, ID_TURMA, ID_DISCIPLINA, ID_ALUNO, DATA) VALUES (3, 'P', 1, 1, 3, '20/05/22')

