use bd_frequencia_escola


INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PEDRO ALVES',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS SILVA',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PAULA MORAES',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS SOUZA',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS CRUZ',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JOAO',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARIA',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('EDUARDO',1)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JO0SE',1)

INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PEDRO ALVES',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS SILVA',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PAULA MORAES',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS SOUZA',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS CRUZ',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JOAO',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARIA',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('EDUARDO',2)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JO0SE',2)

INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PEDRO ALVES',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS SILVA',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PAULA MORAES',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS SOUZA',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS CRUZ',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JOAO',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARIA',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('EDUARDO',3)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JO0SE',3)

INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PEDRO ALVES',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS SILVA',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('PAULA MORAES',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS SOUZA',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MATHEUS CRUZ',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JOAO',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARIA',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('MARCOS',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('EDUARDO',4)
INSERT INTO TB_ALUNO (NOME, ID_TURMA) VALUES ('JO0SE',4)


SELECT * FROM TB_ALUNO