use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_DIM_ALUNO
AS 
BEGIN
	 DECLARE @DATA_CARGA DATE, @COD_ALUNO INT, @NOME VARCHAR(20)
	 DECLARE C_ALUNO CURSOR FOR SELECT DATA_CARGA, COD_ALUNO,NOME_ALUNO FROM TB_AUX_ALUNO
	 OPEN C_ALUNO
	 FETCH C_ALUNO INTO @DATA_CARGA,@COD_ALUNO,@NOME

	 WHILE @@FETCH_STATUS =0
		BEGIN
				
			IF NOT EXISTS(SELECT * FROM DIM_ALUNO WHERE COD_ALUNO = @COD_ALUNO)
				INSERT INTO DIM_ALUNO(COD_ALUNO,NOME_ALUNO)VALUES(@COD_ALUNO,@NOME)
			FETCH C_ALUNO INTO @DATA_CARGA,@COD_ALUNO,@NOME
		END 
		CLOSE C_ALUNO
		DEALLOCATE C_ALUNO
END


EXEC SP_DIM_ALUNO

SELECT * FROM DIM_ALUNO

DELETE  DIM_ALUNO