use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_DIM_TURMA
AS
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(20)
	DECLARE C_TURMA CURSOR FOR SELECT COD_TURMA,NOME_TURMA FROM TB_AUX_TURMA
	OPEN C_TURMA
	FETCH C_TURMA INTO @COD, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS(SELECT COD_TURMA,NOME_TURMA FROM DIM_TURMA WHERE COD_TURMA = @COD)
			INSERT INTO DIM_TURMA (COD_TURMA,NOME_TURMA) VALUES(@COD,@NOME)
			FETCH C_TURMA INTO @COD, @NOME
	END

	CLOSE C_TURMA
	DEALLOCATE C_TURMA

END

EXEC SP_DIM_TURMA

SELECT * FROM DIM_TURMA