use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_FATO_FREQUENCIA
AS
BEGIN
	DECLARE @ID_DISCIPLINA INT, @ID_TURMA INT,
	@ID_ALUNO INT, @ID_ESCOLA INT,@ID_STATUS INT
	,@COD_DISCIPLINA INT, @COD_TURMA INT,
	@COD_ALUNO INT, @COD_ESCOLA INT,@COD_STATUS INT, @DATA DATE,@QUANTIDADE INT
	,@ID_TEMPO INT

	DECLARE C_FATO CURSOR FOR SELECT COD_TURMA,COD_ALUNO,COD_DISCIPLINA
		,COD_ESCOLA,COD_STATUS_FREQUENCIA,DATA_FREQUENCIA
		FROM TB_AUX_FREQUENCIA
	OPEN C_FATO
	FETCH C_FATO INTO @COD_TURMA, @COD_ALUNO, @COD_DISCIPLINA,@COD_ESCOLA,@COD_STATUS,@DATA
	WHILE @@FETCH_STATUS = 0
	BEGIN

		IF EXISTS(SELECT 1 FROM DIM_ALUNO WHERE COD_ALUNO = @COD_ALUNO) AND
		   EXISTS(SELECT 1 FROM DIM_DISCIPLINA WHERE COD_DISCIPLINA = @COD_DISCIPLINA)AND
		   EXISTS(SELECT 1 FROM DIM_ESCOLA WHERE COD_ESCOLA = @COD_ESCOLA)AND
		   EXISTS(SELECT 1 FROM DIM_STATUS_FREQUENCIA WHERE COD_FREQUENCIA = @COD_STATUS)AND
		   EXISTS(SELECT 1 FROM DIM_TURMA WHERE COD_TURMA = @COD_TURMA) AND @DATA IS NOT NULL
			BEGIN
				SET @ID_ALUNO = (SELECT ID_ALUNO FROM DIM_ALUNO WHERE ID_ALUNO = @COD_ALUNO)
				SET @ID_DISCIPLINA = (SELECT ID_DISCIPLINA FROM DIM_DISCIPLINA WHERE ID_DISCIPLINA = @COD_DISCIPLINA)
				SET @ID_ESCOLA = (SELECT ID_ESCOLA FROM DIM_ESCOLA WHERE ID_ESCOLA = @COD_ESCOLA)
				SET @ID_STATUS = (SELECT ID_STATUS_FREQUENCIA FROM DIM_STATUS_FREQUENCIA WHERE ID_STATUS_FREQUENCIA = @COD_STATUS)
				SET @ID_TURMA = (SELECT ID_TURMA FROM DIM_TURMA WHERE ID_TURMA = @COD_TURMA)
				SET @ID_TEMPO = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE DATA = @DATA)

				INSERT INTO FATO_FREQUENCIA(ID_TEMPO,ID_DISCIPLINA,ID_TURMA,ID_ALUNO
				,ID_ESCOLA,ID_STATUS_FREQUENCIA)VALUES
				(@ID_TEMPO,@ID_DISCIPLINA,@ID_TURMA,@ID_ALUNO,@ID_ESCOLA
				,@ID_STATUS)
			END
			IF @COD_STATUS IS NULL
				BEGIN
					INSERT INTO TB_VIO_FREQUENCIA(COD_ALUNO,COD_DISCIPLINA,COD_STATUS_FREQUENCIA,COD_TURMA,
							DATA_ERRO,DATA_FREQUENCIA,VIOLACAO)VALUES(@COD_ALUNO,@COD_DISCIPLINA,@COD_STATUS,@COD_TURMA,GETDATE(),@DATA,'DATA NAO REGISTRADA')
				END
		FETCH C_FATO INTO @COD_TURMA, @COD_ALUNO, @COD_DISCIPLINA,@COD_ESCOLA,@COD_STATUS,@DATA
	END

	CLOSE C_FATO
	DEALLOCATE C_FATO

END


DELETE FATO_FREQUENCIA

EXEC SP_FATO_FREQUENCIA

SELECT * FROM FATO_FREQUENCIA





SELECT SUM(QUANTIDADE), E.NOME_ESCOLA FROM FATO_FREQUENCIA FQ JOIN DIM_ESCOLA E ON (FQ.ID_ESCOLA = E.ID_ESCOLA)
				JOIN DIM_STATUS_FREQUENCIA SF ON (FQ.ID_STATUS_FREQUENCIA = SF.ID_STATUS_FREQUENCIA)
				WHERE SF.STATUS_FREQUENCIA = 'F'
GROUP BY E.NOME_ESCOLA

SELECT SUM(QUANTIDADE), A.NOME_ALUNO FROM FATO_FREQUENCIA FQ JOIN DIM_ALUNO A ON (FQ.ID_ALUNO = A.ID_ALUNO)
				JOIN DIM_STATUS_FREQUENCIA SF ON (FQ.ID_STATUS_FREQUENCIA = SF.ID_STATUS_FREQUENCIA)
				WHERE SF.STATUS_FREQUENCIA = 'F'
GROUP BY A.NOME_ALUNO


SELECT SUM(QUANTIDADE), D.NOME_DISCIPLINA FROM FATO_FREQUENCIA FQ JOIN DIM_DISCIPLINA D ON (FQ.ID_DISCIPLINA = D.ID_DISCIPLINA)
				JOIN DIM_STATUS_FREQUENCIA SF ON (FQ.ID_STATUS_FREQUENCIA = SF.ID_STATUS_FREQUENCIA)
				WHERE SF.STATUS_FREQUENCIA = 'F'
GROUP BY D.NOME_DISCIPLINA


SELECT SUM(QUANTIDADE), T.NOME_TURMA FROM FATO_FREQUENCIA FQ JOIN DIM_TURMA T ON (FQ.ID_TURMA = T.ID_TURMA)
				JOIN DIM_STATUS_FREQUENCIA SF ON (FQ.ID_STATUS_FREQUENCIA = SF.ID_STATUS_FREQUENCIA)
				WHERE SF.STATUS_FREQUENCIA = 'P'
GROUP BY T.NOME_TURMA









SELECT * FROM FATO_FREQUENCIA


SELECT * FROM TB_FREQUENCIA



 