use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_OLTP_FREQUENCIA @DATA_CARGA DATE, @DATA_INICIO DATE,@DATA_FIM DATE
AS
BEGIN
	DELETE TB_AUX_FREQUENCIA
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO TB_AUX_FREQUENCIA(COD_ALUNO,COD_DISCIPLINA,COD_ESCOLA,
		COD_STATUS_FREQUENCIA,DATA_CARGA,DATA_FREQUENCIA,COD_TURMA) SELECT A.ID_ALUNO,D.ID_DISCIPLINA,E.ID_ESCOLA,
		F.ID_FREQUENCIA,@DATA_CARGA,F.DATA,T.ID_TURMA FROM TB_ESCOLA E
		JOIN TB_TURMA T 
		ON (E.ID_ESCOLA = T.ID_ESCOLA) JOIN TB_ALUNO A
		ON (T.ID_TURMA = A.ID_TURMA) JOIN TB_TURMA_DISCIPLINA TD 
		ON (TD.ID_TURMA = T.ID_TURMA) JOIN TB_DISCIPLINA D
		ON (TD.ID_DISCIPLINA = D.ID_DISCIPLINA) JOIN TB_FREQUENCIA F
		ON (TD.ID_DISCIPLINA = F.ID_DISCIPLINA AND TD.ID_TURMA = F.ID_TURMA AND F.ID_ALUNO = A.ID_ALUNO)
		WHERE @DATA_INICIO <= @DATA_FIM
END


DECLARE @DATA DATE
SET @DATA = GETDATE()

EXEC SP_OLTP_FREQUENCIA @DATA
SELECT * FROM TB_AUX_FREQUENCIA