use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_OLTP_DISCIPLINA @DATA_CARGA DATE
AS
BEGIN
	DELETE TB_AUX_DISCIPLINA
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO TB_AUX_DISCIPLINA(COD_DISCIPLINA,DATA_CARGA,NOME_DISCIPLINA) SELECT ID_DISCIPLINA, @DATA_CARGA , NOME FROM TB_DISCIPLINA
END


DECLARE @DATA DATE
SET @DATA = GETDATE()

EXEC SP_OLTP_DISCIPLINA @DATA