use bd_frequencia_escola

CREATE OR ALTER PROCEDURE SP_OLTP_ALUNO @DATA_CARGA DATE
AS
BEGIN
	DELETE TB_AUX_ALUNO
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO TB_AUX_ALUNO(COD_ALUNO,DATA_CARGA,NOME_ALUNO) SELECT A.ID_ALUNO, @DATA_CARGA, A.NOME FROM TB_ALUNO A
END

DECLARE @DATA DATE

SET @DATA = GETDATE()

EXEC SP_OLTP_ALUNO @DATA

SELECT * FROM TB_AUX_ALUNO


select * from TB_ALUNO