use bd_frequencia_escola


CREATE OR ALTER PROCEDURE SP_OLTP_FREQUENCIA @DATA_CARGA DATE, @DATA_INICIO DATE,@DATA_FIM DATE
AS
BEGIN
	DELETE TB_AUX_FREQUENCIA
	WHERE DATA_CARGA = @DATA_CARGA
	INSERT INTO TB_AUX_FREQUENCIA(DATA_CARGA,COD_TURMA,COD_ALUNO,COD_DISCIPLINA,COD_ESCOLA,
	COD_STATUS_FREQUENCIA,DATA_FREQUENCIA)
	SELECT @DATA_CARGA, T.ID_TURMA,A.ID_ALUNO,D.ID_DISCIPLINA,E.ID_ESCOLA,FS.ID_FREQUENCIA_STATUS,F.DATA
	FROM TB_ESCOLA E JOIN TB_TURMA T 
	ON (E.ID_ESCOLA = T.ID_ESCOLA) JOIN
	TB_ALUNO A
	ON(T.ID_TURMA = A.ID_TURMA) JOIN
	TB_TURMA_DISCIPLINA TD
	ON (T.ID_TURMA = TD.ID_TURMA) JOIN
	TB_DISCIPLINA D
	ON(D.ID_DISCIPLINA = TD.ID_DISCIPLINA) JOIN
	TB_FREQUENCIA F
	ON(A.ID_ALUNO = F.ID_ALUNO)JOIN
	FREQUENCIA_STATUS FS
	ON(F.ID_FREQUENCIA_STATUS = FS.ID_FREQUENCIA_STATUS)
	

		WHERE F.data >=  @DATA_Inicio and f.data <= @data_fim
END


DECLARE @DATA DATE
SET @DATA = GETDATE()

EXEC SP_OLTP_FREQUENCIA @DATA , '2022/11/23', '2022/11/24'
SELECT * FROM TB_AUX_FREQUENCIA

SELECT * FROM TB_FREQUENCIA